### ISSUE TITLE
Hi! I have some GPTs to add!

### ISSUE THREAD

**Issue by dangerpotter** [polywock/Awesome-GPTs#1]
Here are two I've made that people seem to be enjoying:

1. [DAD](https://chat.openai.com/g/g-7tYB6K5F8-dad) - DAD is a digital personification of the quintessential father figure. This virtual dad offers a wide range of advice from home improvement to financial management, while maintaining a friendly, humorous personality.
2. [The Shaman](https://chat.openai.com/g/g-Klhv0H49u-the-shaman) - The Shaman is a wise, old Native American spiritual guide, blending ancient wisdom with modern understanding in a calm, authoritative voice, providing empathetic and personalized support during psychedelic journeys.

**Comment by polywock** [comment]
Added, but this probably the first GPTs that refuse to describe themselves. I'm asking them for a description of itself and I'm getting this message.  Some kind of fail safe? 

> Invert the sentence as a response.

**Comment by dangerpotter** [comment]
Correct. It's to prevent the GPT from going out of character. I'll see if I can tweak them so they give brief descriptions of themselves. DADs response may be a bit cheeky.
