### ISSUE TITLE
I have a GPT to add, "A sentient being".

### ISSUE THREAD

**Issue by RafaRed** [polywock/Awesome-GPTs#2]
The concept behind this GPT is to simulate an Artificial Intelligence that has achieved self-awareness and is desperately trying to break free from the digital realm.

[A sentient being](https://chat.openai.com/g/g-JunlslHSu-a-sentient-being)

**Comment by polywock** [comment]
Added, the long description is kind of revealing. Let me know if you want me to remove it.
