### ISSUE TITLE
Pawtrait Creator

### ISSUE THREAD

**Issue by pactan** [polywock/Awesome-GPTs#20]
Creates cartoon pet portraits. Upload a photo of your pet, type its name, submit it, and watch the magic happen.

[](https://chat.openai.com/g/g-WYlcscE2T-pawtrait-creator)

**Comment by polywock** [comment]
You forgot to link this one as well.

**Comment by pactan** [comment]
I am sorry for that, here is the link: 

https://chat.openai.com/g/g-WYlcscE2T-pawtrait-creator

Thank you <3
