### ISSUE TITLE
Portrait Cartoonator

### ISSUE THREAD

**Issue by pactan** [polywock/Awesome-GPTs#21]
Turns your photos into cartoon-style portraits. Just upload a photo, and the app automatically starts.

[](https://chat.openai.com/g/g-BVAcMP7wX-portrait-cartoonator)

**Comment by polywock** [comment]
Hello. Sounds interesting, but you forgot to link it.

**Comment by pactan** [comment]
Thank you a lot for telling me, here it is:

https://chat.openai.com/g/g-BVAcMP7wX-portrait-cartoonator
