### ISSUE TITLE
GPTs of Simeon Penev

### ISSUE THREAD

**Issue by SimonPP123** [polywock/Awesome-GPTs#39]
Hi,

I created some GPTs and I will be very grateful if you publish my GPTs in your collections.
All are in format Name, Description, Author name, Category, Link for the GPT in my website, the ChatGPT link to the builded GPT.
1. 
GPT Builder
Generates ideas for creating GPTs on popular topics
Simeon Penev
Productivity
https://mygptcollection.com/all-gpt-collection/gpt-builder/
https://chat.openai.com/g/g-kY9sadeD5-gpt-builder

2. 
Segment Documentation for Beginners
Expert in Segment.com’s documentation, offering detailed guides and solutions
Simeon Penev
Education
https://mygptcollection.com/all-gpt-collection/segment-documentation-for-beginners/ 
https://chat.openai.com/g/g-oCD3xxOch-segment-documentation-for-beginners

3. 
G Analytics Advisor
Your assistant for understanding Google Analytics 4 data
Simeon Penev
Productivity
https://mygptcollection.com/all-gpt-collection/g-analytics-advisor/ 
https://chat.openai.com/g/g-9fUaUpyYj-g-analytics-advisor

4. 
Data Analysis Fundamentals
Your go-to guide for starting your journey in data analysis
Simeon Penev
Education
https://mygptcollection.com/all-gpt-collection/data-analysis-fundamentals/ 
https://chat.openai.com/g/g-1hgZI0NYQ-data-analysis-fundamentals

5. 
SEO Basics
Mastering the basics of SEO for all users
Simeon Penev
Education
https://mygptcollection.com/all-gpt-collection/seo-basics/ 
https://chat.openai.com/g/g-meFI1mY2R-seo-basics

6. 
Startup Launchpad
Navigating the early stages of entrepreneurship
Simeon Penev
Productivity
https://mygptcollection.com/all-gpt-collection/startup-launchpad/
https://chat.openai.com/g/g-EZ6hBarlZ-startup-launchpad

7. 
Fitness Fundamentals
Adaptable fitness guidance for all levels
Simeon Penev
Lifestyle
https://mygptcollection.com/all-gpt-collection/fitness-fundamentals/ 
https://chat.openai.com/g/g-OAoCVkl9R-fitness-fundamentals

Kind regards,
Simeon Penev

**Comment by polywock** [comment]
Hello. Now that the GPT store has been released, I'm in 'trimming mode', so can't add much to the list. I've added GPT Builder since it's the most used.
