### ISSUE TITLE
Some GPTs for your wonderful collection

### ISSUE THREAD

**Issue by greencat667** [polywock/Awesome-GPTs#7]
**Text Scanner** 
Scans uploaded images for text and displays it formatted.
https://chat.openai.com/g/g-mOAlD4nuM-text-scanner  

**Critical Thinker**
A critical thinker for analyzing questions and improving answers
https://chat.openai.com/g/g-1KHebYbFR-critical-thinker

**Alternative Histories** 
I craft and visualize 'what if' histories.
https://chat.openai.com/g/g-J45g1U3ro-alternative-histories

**Sherlock Holmes**
Access the mind of the world's greatest detective
https://chat.openai.com/g/g-gtobWqG0t-sherlock-holmes

**Comment by polywock** [comment]
Added, also made a new history section.
