### ISSUE TITLE
Some of the GPTs are either not working or set to private mode

### ISSUE THREAD

**Issue by DanBoyDan** [polywock/Awesome-GPTs#8]
Hello, 

Great collection and thanks for your time and I have really not an issuse :)

However I was just testing some of the listed GPTs and for example:

https://chat.openai.com/g/g-dmgFloZ5w-storyteller seems to be set to private or it puts me in endless login loop, while I am logged in
https://chat.openai.com/g/g-ASy25fXeS-interactive-comic-creation-with-jack - same
https://chat.openai.com/g/g-wJVjE9bQs-pic-book-artist - same
https://chat.openai.com/g/g-zuHCfIs9y-hormozi-gpt - replies with errors only

I think you should at least remove those that are currently unusable.

**Comment by polywock** [comment]
ChatGPT bug. I removed the names from the links and it seems to work now.

**Comment by DanBoyDan** [comment]
Thanks :) Now I have to wait for the usage cap to expire

**Comment by polywock** [comment]
Waited 3x today for the quota to reset. I would 100% pay double to get the quota tripled.
